language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
script: bundle exec rake db:reset test:all
env:
  - "RAILS_VERSION=3.2.15"
  - "RAILS_VERSION=4.0.1"
matrix:
  allow_failures:
    - rvm: ruby-head