language: ruby
sudo: false

services:
  - mysql
  - postgresql

rvm:
  - 2.4

services:
  - mysql
  - postgresql

script: "bundle exec rake db:reset test:all"

gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
