sudo: required
language: ruby

rvm:
  - 2.5.0

addons:
  postgresql: "9.6"

services:
  - postgresql

env:
  - MARGINALIA_DB_PORT=5432

sudo: false

before_install:
  - bash -c "yes | gem uninstall -i /home/travis/.rvm/gems/ruby-2.5.0@global rake"

script: bundle exec rake db:reset test:postgresql
