language: ruby
cache: bundler

services:
  - mysql
  - postgresql

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

script: "bundle exec rake db:reset test:all"

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/4.2.api.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile

matrix:
  fast_finish: true
  include:
  - dist: bionic
    rvm:
    - 2.4
    - 2.5
    - 2.6
    - 2.7
  exclude:
    - rvm: 2.7
      gemfile: gemfiles/4.2.gemfile
    - rvm: 2.7
      gemfile: gemfiles/4.2.api.gemfile
